[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "0x45475a"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xbac2de"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font Propo"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Propo"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Propo"
style = "Regular"

[window]
opacity = 0.85
